# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/davide/git_repo/wheeler-language-recognizer/external/WNFA-partition-refinement

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/davide/git_repo/wheeler-language-recognizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/davide/git_repo/wheeler-language-recognizer/CMakeFiles /home/davide/git_repo/wheeler-language-recognizer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/davide/git_repo/wheeler-language-recognizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check32-verb.x

# Build rule for target.
check32-verb.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check32-verb.x
.PHONY : check32-verb.x

# fast build rule for target.
check32-verb.x/fast:
	$(MAKE) -f CMakeFiles/check32-verb.x.dir/build.make CMakeFiles/check32-verb.x.dir/build
.PHONY : check32-verb.x/fast

#=============================================================================
# Target rules for targets named check32.x

# Build rule for target.
check32.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check32.x
.PHONY : check32.x

# fast build rule for target.
check32.x/fast:
	$(MAKE) -f CMakeFiles/check32.x.dir/build.make CMakeFiles/check32.x.dir/build
.PHONY : check32.x/fast

#=============================================================================
# Target rules for targets named part-ref64-verb.x

# Build rule for target.
part-ref64-verb.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 part-ref64-verb.x
.PHONY : part-ref64-verb.x

# fast build rule for target.
part-ref64-verb.x/fast:
	$(MAKE) -f CMakeFiles/part-ref64-verb.x.dir/build.make CMakeFiles/part-ref64-verb.x.dir/build
.PHONY : part-ref64-verb.x/fast

#=============================================================================
# Target rules for targets named merge32-verb.x

# Build rule for target.
merge32-verb.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 merge32-verb.x
.PHONY : merge32-verb.x

# fast build rule for target.
merge32-verb.x/fast:
	$(MAKE) -f CMakeFiles/merge32-verb.x.dir/build.make CMakeFiles/merge32-verb.x.dir/build
.PHONY : merge32-verb.x/fast

#=============================================================================
# Target rules for targets named merge32.x

# Build rule for target.
merge32.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 merge32.x
.PHONY : merge32.x

# fast build rule for target.
merge32.x/fast:
	$(MAKE) -f CMakeFiles/merge32.x.dir/build.make CMakeFiles/merge32.x.dir/build
.PHONY : merge32.x/fast

#=============================================================================
# Target rules for targets named part-ref64.x

# Build rule for target.
part-ref64.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 part-ref64.x
.PHONY : part-ref64.x

# fast build rule for target.
part-ref64.x/fast:
	$(MAKE) -f CMakeFiles/part-ref64.x.dir/build.make CMakeFiles/part-ref64.x.dir/build
.PHONY : part-ref64.x/fast

#=============================================================================
# Target rules for targets named part-ref32-verb.x

# Build rule for target.
part-ref32-verb.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 part-ref32-verb.x
.PHONY : part-ref32-verb.x

# fast build rule for target.
part-ref32-verb.x/fast:
	$(MAKE) -f CMakeFiles/part-ref32-verb.x.dir/build.make CMakeFiles/part-ref32-verb.x.dir/build
.PHONY : part-ref32-verb.x/fast

#=============================================================================
# Target rules for targets named part-ref32.x

# Build rule for target.
part-ref32.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 part-ref32.x
.PHONY : part-ref32.x

# fast build rule for target.
part-ref32.x/fast:
	$(MAKE) -f CMakeFiles/part-ref32.x.dir/build.make CMakeFiles/part-ref32.x.dir/build
.PHONY : part-ref32.x/fast

check_output.o: check_output.cpp.o

.PHONY : check_output.o

# target to build an object file
check_output.cpp.o:
	$(MAKE) -f CMakeFiles/check32-verb.x.dir/build.make CMakeFiles/check32-verb.x.dir/check_output.cpp.o
	$(MAKE) -f CMakeFiles/check32.x.dir/build.make CMakeFiles/check32.x.dir/check_output.cpp.o
.PHONY : check_output.cpp.o

check_output.i: check_output.cpp.i

.PHONY : check_output.i

# target to preprocess a source file
check_output.cpp.i:
	$(MAKE) -f CMakeFiles/check32-verb.x.dir/build.make CMakeFiles/check32-verb.x.dir/check_output.cpp.i
	$(MAKE) -f CMakeFiles/check32.x.dir/build.make CMakeFiles/check32.x.dir/check_output.cpp.i
.PHONY : check_output.cpp.i

check_output.s: check_output.cpp.s

.PHONY : check_output.s

# target to generate assembly for a file
check_output.cpp.s:
	$(MAKE) -f CMakeFiles/check32-verb.x.dir/build.make CMakeFiles/check32-verb.x.dir/check_output.cpp.s
	$(MAKE) -f CMakeFiles/check32.x.dir/build.make CMakeFiles/check32.x.dir/check_output.cpp.s
.PHONY : check_output.cpp.s

exe.o: exe.cpp.o

.PHONY : exe.o

# target to build an object file
exe.cpp.o:
	$(MAKE) -f CMakeFiles/part-ref64-verb.x.dir/build.make CMakeFiles/part-ref64-verb.x.dir/exe.cpp.o
	$(MAKE) -f CMakeFiles/part-ref64.x.dir/build.make CMakeFiles/part-ref64.x.dir/exe.cpp.o
	$(MAKE) -f CMakeFiles/part-ref32-verb.x.dir/build.make CMakeFiles/part-ref32-verb.x.dir/exe.cpp.o
	$(MAKE) -f CMakeFiles/part-ref32.x.dir/build.make CMakeFiles/part-ref32.x.dir/exe.cpp.o
.PHONY : exe.cpp.o

exe.i: exe.cpp.i

.PHONY : exe.i

# target to preprocess a source file
exe.cpp.i:
	$(MAKE) -f CMakeFiles/part-ref64-verb.x.dir/build.make CMakeFiles/part-ref64-verb.x.dir/exe.cpp.i
	$(MAKE) -f CMakeFiles/part-ref64.x.dir/build.make CMakeFiles/part-ref64.x.dir/exe.cpp.i
	$(MAKE) -f CMakeFiles/part-ref32-verb.x.dir/build.make CMakeFiles/part-ref32-verb.x.dir/exe.cpp.i
	$(MAKE) -f CMakeFiles/part-ref32.x.dir/build.make CMakeFiles/part-ref32.x.dir/exe.cpp.i
.PHONY : exe.cpp.i

exe.s: exe.cpp.s

.PHONY : exe.s

# target to generate assembly for a file
exe.cpp.s:
	$(MAKE) -f CMakeFiles/part-ref64-verb.x.dir/build.make CMakeFiles/part-ref64-verb.x.dir/exe.cpp.s
	$(MAKE) -f CMakeFiles/part-ref64.x.dir/build.make CMakeFiles/part-ref64.x.dir/exe.cpp.s
	$(MAKE) -f CMakeFiles/part-ref32-verb.x.dir/build.make CMakeFiles/part-ref32-verb.x.dir/exe.cpp.s
	$(MAKE) -f CMakeFiles/part-ref32.x.dir/build.make CMakeFiles/part-ref32.x.dir/exe.cpp.s
.PHONY : exe.cpp.s

external/malloc_count/malloc_count.o: external/malloc_count/malloc_count.c.o

.PHONY : external/malloc_count/malloc_count.o

# target to build an object file
external/malloc_count/malloc_count.c.o:
	$(MAKE) -f CMakeFiles/check32-verb.x.dir/build.make CMakeFiles/check32-verb.x.dir/external/malloc_count/malloc_count.c.o
	$(MAKE) -f CMakeFiles/check32.x.dir/build.make CMakeFiles/check32.x.dir/external/malloc_count/malloc_count.c.o
	$(MAKE) -f CMakeFiles/part-ref64-verb.x.dir/build.make CMakeFiles/part-ref64-verb.x.dir/external/malloc_count/malloc_count.c.o
	$(MAKE) -f CMakeFiles/merge32-verb.x.dir/build.make CMakeFiles/merge32-verb.x.dir/external/malloc_count/malloc_count.c.o
	$(MAKE) -f CMakeFiles/merge32.x.dir/build.make CMakeFiles/merge32.x.dir/external/malloc_count/malloc_count.c.o
	$(MAKE) -f CMakeFiles/part-ref64.x.dir/build.make CMakeFiles/part-ref64.x.dir/external/malloc_count/malloc_count.c.o
	$(MAKE) -f CMakeFiles/part-ref32-verb.x.dir/build.make CMakeFiles/part-ref32-verb.x.dir/external/malloc_count/malloc_count.c.o
	$(MAKE) -f CMakeFiles/part-ref32.x.dir/build.make CMakeFiles/part-ref32.x.dir/external/malloc_count/malloc_count.c.o
.PHONY : external/malloc_count/malloc_count.c.o

external/malloc_count/malloc_count.i: external/malloc_count/malloc_count.c.i

.PHONY : external/malloc_count/malloc_count.i

# target to preprocess a source file
external/malloc_count/malloc_count.c.i:
	$(MAKE) -f CMakeFiles/check32-verb.x.dir/build.make CMakeFiles/check32-verb.x.dir/external/malloc_count/malloc_count.c.i
	$(MAKE) -f CMakeFiles/check32.x.dir/build.make CMakeFiles/check32.x.dir/external/malloc_count/malloc_count.c.i
	$(MAKE) -f CMakeFiles/part-ref64-verb.x.dir/build.make CMakeFiles/part-ref64-verb.x.dir/external/malloc_count/malloc_count.c.i
	$(MAKE) -f CMakeFiles/merge32-verb.x.dir/build.make CMakeFiles/merge32-verb.x.dir/external/malloc_count/malloc_count.c.i
	$(MAKE) -f CMakeFiles/merge32.x.dir/build.make CMakeFiles/merge32.x.dir/external/malloc_count/malloc_count.c.i
	$(MAKE) -f CMakeFiles/part-ref64.x.dir/build.make CMakeFiles/part-ref64.x.dir/external/malloc_count/malloc_count.c.i
	$(MAKE) -f CMakeFiles/part-ref32-verb.x.dir/build.make CMakeFiles/part-ref32-verb.x.dir/external/malloc_count/malloc_count.c.i
	$(MAKE) -f CMakeFiles/part-ref32.x.dir/build.make CMakeFiles/part-ref32.x.dir/external/malloc_count/malloc_count.c.i
.PHONY : external/malloc_count/malloc_count.c.i

external/malloc_count/malloc_count.s: external/malloc_count/malloc_count.c.s

.PHONY : external/malloc_count/malloc_count.s

# target to generate assembly for a file
external/malloc_count/malloc_count.c.s:
	$(MAKE) -f CMakeFiles/check32-verb.x.dir/build.make CMakeFiles/check32-verb.x.dir/external/malloc_count/malloc_count.c.s
	$(MAKE) -f CMakeFiles/check32.x.dir/build.make CMakeFiles/check32.x.dir/external/malloc_count/malloc_count.c.s
	$(MAKE) -f CMakeFiles/part-ref64-verb.x.dir/build.make CMakeFiles/part-ref64-verb.x.dir/external/malloc_count/malloc_count.c.s
	$(MAKE) -f CMakeFiles/merge32-verb.x.dir/build.make CMakeFiles/merge32-verb.x.dir/external/malloc_count/malloc_count.c.s
	$(MAKE) -f CMakeFiles/merge32.x.dir/build.make CMakeFiles/merge32.x.dir/external/malloc_count/malloc_count.c.s
	$(MAKE) -f CMakeFiles/part-ref64.x.dir/build.make CMakeFiles/part-ref64.x.dir/external/malloc_count/malloc_count.c.s
	$(MAKE) -f CMakeFiles/part-ref32-verb.x.dir/build.make CMakeFiles/part-ref32-verb.x.dir/external/malloc_count/malloc_count.c.s
	$(MAKE) -f CMakeFiles/part-ref32.x.dir/build.make CMakeFiles/part-ref32.x.dir/external/malloc_count/malloc_count.c.s
.PHONY : external/malloc_count/malloc_count.c.s

lib/part_ref.o: lib/part_ref.cpp.o

.PHONY : lib/part_ref.o

# target to build an object file
lib/part_ref.cpp.o:
	$(MAKE) -f CMakeFiles/part-ref64-verb.x.dir/build.make CMakeFiles/part-ref64-verb.x.dir/lib/part_ref.cpp.o
	$(MAKE) -f CMakeFiles/merge32-verb.x.dir/build.make CMakeFiles/merge32-verb.x.dir/lib/part_ref.cpp.o
	$(MAKE) -f CMakeFiles/merge32.x.dir/build.make CMakeFiles/merge32.x.dir/lib/part_ref.cpp.o
	$(MAKE) -f CMakeFiles/part-ref64.x.dir/build.make CMakeFiles/part-ref64.x.dir/lib/part_ref.cpp.o
	$(MAKE) -f CMakeFiles/part-ref32-verb.x.dir/build.make CMakeFiles/part-ref32-verb.x.dir/lib/part_ref.cpp.o
	$(MAKE) -f CMakeFiles/part-ref32.x.dir/build.make CMakeFiles/part-ref32.x.dir/lib/part_ref.cpp.o
.PHONY : lib/part_ref.cpp.o

lib/part_ref.i: lib/part_ref.cpp.i

.PHONY : lib/part_ref.i

# target to preprocess a source file
lib/part_ref.cpp.i:
	$(MAKE) -f CMakeFiles/part-ref64-verb.x.dir/build.make CMakeFiles/part-ref64-verb.x.dir/lib/part_ref.cpp.i
	$(MAKE) -f CMakeFiles/merge32-verb.x.dir/build.make CMakeFiles/merge32-verb.x.dir/lib/part_ref.cpp.i
	$(MAKE) -f CMakeFiles/merge32.x.dir/build.make CMakeFiles/merge32.x.dir/lib/part_ref.cpp.i
	$(MAKE) -f CMakeFiles/part-ref64.x.dir/build.make CMakeFiles/part-ref64.x.dir/lib/part_ref.cpp.i
	$(MAKE) -f CMakeFiles/part-ref32-verb.x.dir/build.make CMakeFiles/part-ref32-verb.x.dir/lib/part_ref.cpp.i
	$(MAKE) -f CMakeFiles/part-ref32.x.dir/build.make CMakeFiles/part-ref32.x.dir/lib/part_ref.cpp.i
.PHONY : lib/part_ref.cpp.i

lib/part_ref.s: lib/part_ref.cpp.s

.PHONY : lib/part_ref.s

# target to generate assembly for a file
lib/part_ref.cpp.s:
	$(MAKE) -f CMakeFiles/part-ref64-verb.x.dir/build.make CMakeFiles/part-ref64-verb.x.dir/lib/part_ref.cpp.s
	$(MAKE) -f CMakeFiles/merge32-verb.x.dir/build.make CMakeFiles/merge32-verb.x.dir/lib/part_ref.cpp.s
	$(MAKE) -f CMakeFiles/merge32.x.dir/build.make CMakeFiles/merge32.x.dir/lib/part_ref.cpp.s
	$(MAKE) -f CMakeFiles/part-ref64.x.dir/build.make CMakeFiles/part-ref64.x.dir/lib/part_ref.cpp.s
	$(MAKE) -f CMakeFiles/part-ref32-verb.x.dir/build.make CMakeFiles/part-ref32-verb.x.dir/lib/part_ref.cpp.s
	$(MAKE) -f CMakeFiles/part-ref32.x.dir/build.make CMakeFiles/part-ref32.x.dir/lib/part_ref.cpp.s
.PHONY : lib/part_ref.cpp.s

merge.o: merge.cpp.o

.PHONY : merge.o

# target to build an object file
merge.cpp.o:
	$(MAKE) -f CMakeFiles/merge32-verb.x.dir/build.make CMakeFiles/merge32-verb.x.dir/merge.cpp.o
	$(MAKE) -f CMakeFiles/merge32.x.dir/build.make CMakeFiles/merge32.x.dir/merge.cpp.o
.PHONY : merge.cpp.o

merge.i: merge.cpp.i

.PHONY : merge.i

# target to preprocess a source file
merge.cpp.i:
	$(MAKE) -f CMakeFiles/merge32-verb.x.dir/build.make CMakeFiles/merge32-verb.x.dir/merge.cpp.i
	$(MAKE) -f CMakeFiles/merge32.x.dir/build.make CMakeFiles/merge32.x.dir/merge.cpp.i
.PHONY : merge.cpp.i

merge.s: merge.cpp.s

.PHONY : merge.s

# target to generate assembly for a file
merge.cpp.s:
	$(MAKE) -f CMakeFiles/merge32-verb.x.dir/build.make CMakeFiles/merge32-verb.x.dir/merge.cpp.s
	$(MAKE) -f CMakeFiles/merge32.x.dir/build.make CMakeFiles/merge32.x.dir/merge.cpp.s
.PHONY : merge.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... check32-verb.x"
	@echo "... check32.x"
	@echo "... part-ref64-verb.x"
	@echo "... edit_cache"
	@echo "... merge32-verb.x"
	@echo "... merge32.x"
	@echo "... part-ref64.x"
	@echo "... part-ref32-verb.x"
	@echo "... rebuild_cache"
	@echo "... part-ref32.x"
	@echo "... check_output.o"
	@echo "... check_output.i"
	@echo "... check_output.s"
	@echo "... exe.o"
	@echo "... exe.i"
	@echo "... exe.s"
	@echo "... external/malloc_count/malloc_count.o"
	@echo "... external/malloc_count/malloc_count.i"
	@echo "... external/malloc_count/malloc_count.s"
	@echo "... lib/part_ref.o"
	@echo "... lib/part_ref.i"
	@echo "... lib/part_ref.s"
	@echo "... merge.o"
	@echo "... merge.i"
	@echo "... merge.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

